FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y python3-pip \
    && pip3 install --upgrade pip
	
RUN pip3 install numpy pandas matplotlib seaborn plotly sklearn statistics

WORKDIR /app

COPY Iris.py /app

CMD ["python3","-u","./Iris.py"]